# The MOSPI dataset is a collection of official statistical data released by the Ministry of Statistics and Programme Implementation

In [2]:
import numpy as np     # Used for high-speed numerical computations and multi-dimensional array operations.
import pandas as pd    # Used for intuitive cleaning, manipulation, and analysis of structured, tabular data.

### MOSPI Level 5 Dataset Overview

        The MOSPI Level-5 dataset represents household-level micro consumption data from HCES survey, capturing detailed 
        food and non-food expenditure patterns.
    
        It is used to convert raw item-level codes into meaningful nutrition and consumption categories 
        (cereals, pulses, dairy, etc.), enabling socio-economic interpretation.
    
        In this project, it forms the foundation for building food security, welfare, and wellbeing indices at household 
        and district scale.
        
        This dataset is essential for transforming raw survey codes into policy-relevant development indicators for spatial 
        inequality analysis.

In [3]:
mos_lv5 = pd.read_csv("LEVEL - 05 ( Sec 5  6).csv")
print(mos_lv5.shape)

(12754437, 25)

In [4]:
mos_lv5.head(5)

,Survey_Name,Year,FSU_Serial_No,Sector,State,NSS_Region,District,Stratum,Sub_stratum,Panel,...,Sample_Household_No,Questionnaire_No,Level,Item_Code,OutOfHome_Consumption_Quantity,OutOfHome_Consumption_Value,Total_Consumption_Quantity,Total_Consumption_Value,Source,Multiplier
0,HCES,2024,46667,1,1,12,6,13,1,2,...,1,F,5,2,10.0,250.0,10.0,250.0,2.0,16669
1,HCES,2024,46667,1,1,12,6,13,1,2,...,1,F,5,3,NaN,NaN,0.5,160.0,1.0,16669
2,HCES,2024,46667,1,1,12,6,13,1,2,...,1,F,5,101,NaN,NaN,15.0,225.0,1.0,16669
3,HCES,2024,46667,1,1,12,6,13,1,2,...,1,F,5,107,NaN,NaN,10.0,130.0,1.0,16669
4,HCES,2024,46667,1,1,12,6,13,1,2,...,1,F,5,108,NaN,NaN,5.0,165.0,1.0,16669

In [5]:
mos_lv5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12754437 entries, 0 to 12754436
Data columns (total 25 columns):
 #   Column                          Dtype
---  ------                          -----
 0   Survey_Name                     object
 1   Year                            int64
 2   FSU_Serial_No                   int64
 3   Sector                          int64
 4   State                           int64
 5   NSS_Region                      int64
 6   District                        int64
 7   Stratum                         int64
 8   Sub_stratum                     int64
 9   Panel                           int64
 10  Sub_sample                      int64
 11  FOD_Sub_Region                  int64
 12  Sample_SU_No                    int64
 13  Sample_Sub_Division_No          float64
 14  Second_Stage_Stratum_No         int64
 15  Sample_Household_No             int64
 16  Questionnaire_No                object
 17  Level                           int64
 18  Item_Code                       int64
 19  OutOfHome_Consumption_Quantity  float64
 20  OutOfHome_Consumption_Value     float64
 21  Total_Consumption_Quantity      float64
 22  Total_Consumption_Value         float64
 23  Source                          float64
 24  Multiplier                      int64
dtypes: float64(6), int64(17), object(2)
memory usage: 2.4+ GB

In [6]:
# Checking Null Values

mos_lv5.isnull().sum()

Survey_Name                              0
Year                                     0
FSU_Serial_No                            0
Sector                                   0
State                                    0
NSS_Region                               0
District                                 0
Stratum                                  0
Sub_stratum                              0
Panel                                    0
Sub_sample                               0
FOD_Sub_Region                           0
Sample_SU_No                             0
Sample_Sub_Division_No            12653703
Second_Stage_Stratum_No                  0
Sample_Household_No                      0
Questionnaire_No                         0
Level                                    0
Item_Code                                0
OutOfHome_Consumption_Quantity    12311988
OutOfHome_Consumption_Value       12212641
Total_Consumption_Quantity         1399254
Total_Consumption_Value             230186
Source                             2937293
Multiplier                               0
dtype: int64

In [7]:
# checking item code

np.sort(mos_lv5['Item_Code'].unique())

array([  1,   2,   3,   4,   5,   6,   7,   8,  10,  11,  55,  56,  59,
        61,  62,  63,  64,  65,  66,  67,  68,  70,  71,  72,  73,  74,
        75,  92,  93,  94,  95, 101, 102, 103, 105, 106, 107, 108, 110,
       111, 112, 114, 115, 116, 117, 118, 120, 121, 122, 129, 139, 140,
       141, 142, 143, 144, 145, 146, 148, 150, 152, 158, 159, 160, 162,
       163, 164, 165, 166, 167, 169, 170, 171, 172, 173, 174, 175, 178,
       179, 180, 181, 182, 183, 184, 185, 188, 189, 190, 191, 192, 193,
       194, 195, 196, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
       210, 211, 212, 213, 214, 215, 216, 217, 219, 220, 221, 222, 223,
       224, 225, 226, 227, 228, 230, 231, 232, 233, 234, 235, 236, 237,
       238, 239, 240, 241, 242, 243, 245, 246, 247, 249, 250, 251, 252,
       253, 254, 255, 256, 257, 258, 260, 261, 263, 269, 270, 271, 272,
       273, 274, 275, 276, 278, 279])

In [8]:
# Handle Missing Values

consumption_cols = [
    "OutOfHome_Consumption_Value",
    "OutOfHome_Consumption_Quantity",
    "Total_Consumption_Value",
    "Total_Consumption_Quantity"
]

mos_lv5[consumption_cols] = (
    mos_lv5[consumption_cols]
    .fillna(0)
)

In [9]:
# Create Household ID

mos_lv5["HH_ID"] = (
    mos_lv5["FSU_Serial_No"].astype(str)
    + "_"
    + mos_lv5["Sample_Household_No"].astype(str)
)

In [10]:
# Create Working Dataset

mos = mos_lv5.copy()

# Food Category Mapping

food_mapping = {

    # Cereals
    1:"Cereals", 2:"Cereals",
    61:"Cereals", 62:"Cereals", 70:"Cereals",
    101:"Cereals", 102:"Cereals", 103:"Cereals",
    105:"Cereals", 106:"Cereals", 107:"Cereals",
    108:"Cereals", 110:"Cereals", 111:"Cereals",
    112:"Cereals", 114:"Cereals", 122:"Cereals",
    139:"Cereals",

    # Pulses
    71:"Pulses", 72:"Pulses",
    140:"Pulses", 141:"Pulses", 142:"Pulses",
    143:"Pulses", 144:"Pulses", 145:"Pulses",
    146:"Pulses", 148:"Pulses", 150:"Pulses",
    152:"Pulses",

    # Sugar
    73:"Sugar", 74:"Sugar",
    170:"Sugar", 171:"Sugar", 172:"Sugar",
    173:"Sugar", 174:"Sugar", 175:"Sugar",
    178:"Sugar",

    # Milk Products
    3:"Milk_Products", 4:"Milk_Products",
    5:"Milk_Products", 92:"Milk_Products",
    160:"Milk_Products", 162:"Milk_Products",
    163:"Milk_Products", 164:"Milk_Products",
    165:"Milk_Products", 166:"Milk_Products",

    # Vegetables
    200:"Vegetables", 201:"Vegetables",
    202:"Vegetables", 203:"Vegetables",
    204:"Vegetables", 205:"Vegetables",
    206:"Vegetables", 207:"Vegetables",
    208:"Vegetables", 210:"Vegetables",
    211:"Vegetables", 212:"Vegetables",
    213:"Vegetables", 214:"Vegetables",
    215:"Vegetables", 216:"Vegetables",
    217:"Vegetables",

    # Fruits
    93:"Fruits",
    220:"Fruits",221:"Fruits",222:"Fruits",
    223:"Fruits",224:"Fruits",225:"Fruits",
    226:"Fruits",227:"Fruits",228:"Fruits",
    230:"Fruits",231:"Fruits",232:"Fruits",
    233:"Fruits",234:"Fruits",235:"Fruits",
    236:"Fruits",237:"Fruits",238:"Fruits",

    # Egg Fish Meat
    190:"Egg_Fish_Meat",191:"Egg_Fish_Meat",
    192:"Egg_Fish_Meat",193:"Egg_Fish_Meat",
    194:"Egg_Fish_Meat",195:"Egg_Fish_Meat",
    196:"Egg_Fish_Meat",

    # Edible Oil
    75:"Edible_Oil",95:"Edible_Oil",
    181:"Edible_Oil",182:"Edible_Oil",
    183:"Edible_Oil",184:"Edible_Oil",
    188:"Edible_Oil",

    # Spices
    250:"Spices",251:"Spices",
    252:"Spices",253:"Spices",
    254:"Spices",255:"Spices",
    256:"Spices",257:"Spices",
    258:"Spices",260:"Spices",
    261:"Spices",263:"Spices",

    # Beverages
    11:"Beverages",
    270:"Beverages",271:"Beverages",
    272:"Beverages",273:"Beverages",
    274:"Beverages",275:"Beverages",
    276:"Beverages",278:"Beverages"
}

In [11]:
# Assign Food Categories

mos["Food_Category"] = (
    mos["Item_Code"]
    .map(food_mapping)
)

# Keep Food Records 

mos = mos[
    mos["Food_Category"].notna()
].copy()

print(mos.shape)

(9665988, 27)

In [12]:
# Create Household Food Matrix

food_hh = (
    mos.pivot_table(
        index=[
            "HH_ID",
            "State",
            "District",
            "Sector"
        ],
        columns="Food_Category",
        values="Total_Consumption_Value",
        aggfunc="sum",
        fill_value=0
    )
    .reset_index()
)

In [13]:
# Ensure All Food Columns Exist

food_cols = [
    "Cereals",
    "Pulses",
    "Milk_Products",
    "Vegetables",
    "Fruits",
    "Egg_Fish_Meat",
    "Edible_Oil",
    "Spices",
    "Beverages",
    "Sugar"
]

for col in food_cols:
    if col not in food_hh.columns:
        food_hh[col] = 0

In [14]:
# Add Household Weights

hh_weight = (
    mos.groupby("HH_ID")["Multiplier"]
    .first()
    .reset_index()
)

food_hh = food_hh.merge(
    hh_weight,
    on="HH_ID",
    how="left"
)

In [15]:
# Calculate Total Food Expenditure

food_hh["Total_Food_Value"] = (
    food_hh[food_cols]
    .sum(axis=1)
)

# Calculate Out-of-Home Food Expenditure

ooh = (
    mos.groupby("HH_ID")
    ["OutOfHome_Consumption_Value"]
    .sum()
    .reset_index()
)

ooh.rename(
    columns={
        "OutOfHome_Consumption_Value":
        "OutOfHome_Food_Value"
    },
    inplace=True
)

In [16]:
# Merge Out-of-Home Data

food_hh = food_hh.merge(
    ooh,
    on="HH_ID",
    how="left"
)

food_hh["OutOfHome_Food_Value"] = (
    food_hh["OutOfHome_Food_Value"]
    .fillna(0)
)

In [17]:
# Food Diversity Score
food_hh["Food_Items_Count"] = (
    food_hh[food_cols] > 0
).sum(axis=1)

food_hh["Diet_Diversity_Score"] = (
    food_hh["Food_Items_Count"] / 10
)

# Nutrition Score
nutrition_cols = [
    "Milk_Products",
    "Fruits",
    "Vegetables",
    "Egg_Fish_Meat",
    "Pulses"
]

food_hh["Nutrition_Score"] = (
    (
        food_hh[nutrition_cols] > 0
    ).sum(axis=1)
    / len(nutrition_cols)
)

# Protein Score
food_hh["Protein_Value"] = (
    food_hh["Pulses"]
    + food_hh["Milk_Products"]
    + food_hh["Egg_Fish_Meat"]
)

food_hh["Protein_Score"] = (
    food_hh["Protein_Value"]
    .rank(pct=True)
)

# Food Security Score
food_hh["Food_Security_Score"] = (
    food_hh["Total_Food_Value"]
    .rank(pct=True)
)

In [18]:
# Out-of-Home Ratio

food_hh["OutOfHome_Ratio"] = np.where(
    food_hh["Total_Food_Value"] > 0,
    food_hh["OutOfHome_Food_Value"]
    /
    food_hh["Total_Food_Value"],
    0
)

food_hh["OutOfHome_Ratio"] = (
    food_hh["OutOfHome_Ratio"]
    .clip(upper=1)
)

In [19]:
# Overall Food Wellbeing Index

food_hh["Overall_Food_Wellbeing_Index"] = (
      0.30 * food_hh["Diet_Diversity_Score"]
    + 0.25 * food_hh["Nutrition_Score"]
    + 0.25 * food_hh["Food_Security_Score"]
    + 0.20 * food_hh["Protein_Score"]
)

In [20]:
# Final dataset of MOSPI Level-5 Dataset (HCES)

food_hh.head(5)

,HH_ID,State,District,Sector,Beverages,Cereals,Edible_Oil,Egg_Fish_Meat,Fruits,Milk_Products,...,Total_Food_Value,OutOfHome_Food_Value,Food_Items_Count,Diet_Diversity_Score,Nutrition_Score,Protein_Value,Protein_Score,Food_Security_Score,OutOfHome_Ratio,Overall_Food_Wellbeing_Index
0,22300_1,34,2,2,601.0,4207.0,656.0,1422.0,845.0,860.0,...,12045.0,0.0,10,1.0,1.0,3779.0,0.979342,0.988556,0.0,0.993007
1,22300_10,34,2,2,226.0,895.0,174.0,348.0,450.0,290.0,...,3093.0,0.0,10,1.0,1.0,918.0,0.477151,0.557959,0.0,0.784920
2,22300_11,34,2,2,256.0,1625.0,172.0,854.0,415.0,440.0,...,4903.0,0.0,10,1.0,1.0,1801.0,0.846943,0.838716,0.0,0.929068
3,22300_12,34,2,2,353.0,2235.0,270.0,1170.0,425.0,590.0,...,6965.0,0.0,10,1.0,1.0,2730.0,0.944872,0.930171,0.0,0.971517
4,22300_13,34,2,2,216.0,1455.0,228.0,648.0,430.0,440.0,...,4821.0,0.0,10,1.0,1.0,1777.0,0.842286,0.832167,0.0,0.926499

In [21]:
# Checking Null Values

food_hh.isnull().sum()

HH_ID                           0
State                           0
District                        0
Sector                          0
Beverages                       0
Cereals                         0
Edible_Oil                      0
Egg_Fish_Meat                   0
Fruits                          0
Milk_Products                   0
Pulses                          0
Spices                          0
Sugar                           0
Vegetables                      0
Multiplier                      0
Total_Food_Value                0
OutOfHome_Food_Value            0
Food_Items_Count                0
Diet_Diversity_Score            0
Nutrition_Score                 0
Protein_Value                   0
Protein_Score                   0
Food_Security_Score             0
OutOfHome_Ratio                 0
Overall_Food_Wellbeing_Index    0
dtype: int64

In [22]:
food_hh.describe()

,State,District,Sector,Beverages,Cereals,Edible_Oil,Egg_Fish_Meat,Fruits,Milk_Products,Pulses,...,Total_Food_Value,OutOfHome_Food_Value,Food_Items_Count,Diet_Diversity_Score,Nutrition_Score,Protein_Value,Protein_Score,Food_Security_Score,OutOfHome_Ratio,Overall_Food_Wellbeing_Index
count,226445.000000,226445.000000,226445.000000,226445.000000,226445.000000,226445.000000,226445.000000,226445.000000,226445.000000,226445.000000,...,226445.000000,226445.000000,226445.000000,226445.000000,226445.000000,226445.000000,226445.000000,226445.000000,226445.000000,226445.000000
mean,18.857418,15.737159,1.414595,156.573671,1118.385679,136.881967,294.717477,166.091484,454.055568,416.557601,...,3405.110063,286.826130,9.533670,0.953367,0.924844,1165.330645,0.500002,0.500002,0.071929,0.742222
std,9.395586,13.210011,0.492653,189.750561,889.502457,117.523952,428.175988,185.581399,543.746917,322.181767,...,2355.263791,716.604477,1.141281,0.114128,0.141737,918.666348,0.288676,0.288676,0.143372,0.162947
min,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004259,0.000018,0.000000,0.000856
25%,9.000000,6.000000,1.000000,50.000000,551.000000,74.000000,30.000000,50.000000,152.000000,210.000000,...,2015.000000,0.000000,9.000000,0.900000,0.800000,620.000000,0.250112,0.249915,0.000000,0.640259
50%,19.000000,12.000000,1.000000,104.000000,920.000000,118.000000,190.000000,110.000000,305.000000,345.000000,...,2876.000000,0.000000,10.000000,1.000000,1.000000,950.000000,0.500079,0.500079,0.000000,0.754808
75%,27.000000,22.000000,2.000000,190.000000,1430.000000,166.000000,388.000000,210.000000,560.000000,527.000000,...,4070.000000,150.000000,10.000000,1.000000,1.000000,1430.000000,0.749908,0.749950,0.052161,0.866668
max,37.000000,71.000000,2.000000,5760.000000,23780.000000,19950.000000,35000.000000,6130.000000,64420.000000,8070.000000,...,148879.000000,32450.000000,10.000000,1.000000,1.000000,72490.000000,1.000000,1.000000,1.000000,0.999996

In [23]:
# Final shape MOSPI Level-5 Dataset (HCES)

food_hh.shape

(226445, 25)

In [24]:
# Checking Duplicate Values

food_hh.duplicated().sum()

np.int64(0)

### MOSPI Level-9 Dataset (HCES)

        The MOSPI Level-9 dataset contains household-level detailed expenditure microdata covering key non-food welfare 
        dimensions such as education, health, hygiene, transport, and housing.
        
        It is used to transform raw item codes into structured welfare categories, enabling multidimensional
        socio-economic analysis.
        
        In this project, it supports the construction of Welfare Diversity, Human Development, and Quality-of-Life indices 
        at household and district level.
        
        This dataset is critical for capturing the non-consumption dimensions of development required for spatial inequality
        and wellbeing modeling.

In [25]:
mos_lv9 = pd.read_csv("LEVEL - 09 (Section 9  10  11).csv")
print(mos_lv9.shape)

(8259120, 21)

In [26]:
mos_lv9.head(5)

,Survey_Name,Year,FSU_Serial_No,Sector,State,NSS_Region,District,Stratum,Sub_stratum,Panel,...,FOD_Sub_Region,Sample_SU_No,Sample_Sub_Division_No,Second_Stage_Stratum_No,Sample_Household_No,Questionnaire_No,Level,Item_Code_9_1_to_11_4,Value_Rs_9_1_to_11_4,Multiplier
0,HCES,2024,46667,1,1,12,6,13,1,2,...,110,3,NaN,2,1,C,9,17,100,16669
1,HCES,2024,46667,1,1,12,6,13,1,2,...,110,3,NaN,2,1,C,9,18,50,16669
2,HCES,2024,46667,1,1,12,6,13,1,2,...,110,3,NaN,2,1,C,9,20,230,16669
3,HCES,2024,46667,1,1,12,6,13,1,2,...,110,3,NaN,2,1,C,9,21,200,16669
4,HCES,2024,46667,1,1,12,6,13,1,2,...,110,3,NaN,2,1,C,9,400,1900,16669

In [27]:
mos_lv9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8259120 entries, 0 to 8259119
Data columns (total 21 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Survey_Name              object
 1   Year                     int64
 2   FSU_Serial_No            int64
 3   Sector                   int64
 4   State                    int64
 5   NSS_Region               int64
 6   District                 int64
 7   Stratum                  int64
 8   Sub_stratum              int64
 9   Panel                    int64
 10  Sub_sample               int64
 11  FOD_Sub_Region           int64
 12  Sample_SU_No             int64
 13  Sample_Sub_Division_No   float64
 14  Second_Stage_Stratum_No  int64
 15  Sample_Household_No      int64
 16  Questionnaire_No         object
 17  Level                    int64
 18  Item_Code_9_1_to_11_4    int64
 19  Value_Rs_9_1_to_11_4     int64
 20  Multiplier               int64
dtypes: float64(1), int64(18), object(2)
memory usage: 1.3+ GB

In [28]:
mos_lv9.isnull().sum()

Survey_Name                      0
Year                             0
FSU_Serial_No                    0
Sector                           0
State                            0
NSS_Region                       0
District                         0
Stratum                          0
Sub_stratum                      0
Panel                            0
Sub_sample                       0
FOD_Sub_Region                   0
Sample_SU_No                     0
Sample_Sub_Division_No     8192301
Second_Stage_Stratum_No          0
Sample_Household_No              0
Questionnaire_No                 0
Level                            0
Item_Code_9_1_to_11_4            0
Value_Rs_9_1_to_11_4             0
Multiplier                       0
dtype: int64

In [29]:
# checking item code

np.sort(mos_lv9['Item_Code_9_1_to_11_4'].unique())

array([ 16,  17,  18,  20,  21,  22,  23,  24,  25,  26,  27,  28, 400,
       401, 402, 404, 405, 406, 408, 409, 410, 411, 412, 413, 414, 419,
       420, 421, 422, 423, 424, 429, 430, 433, 435, 437, 438, 439, 450,
       451, 452, 453, 454, 455, 456, 457, 459, 460, 461, 462, 463, 464,
       465, 466, 467, 468, 470, 471, 472, 479, 480, 481, 482, 483, 484,
       485, 486, 487, 488, 490, 492, 493, 494, 495, 496, 497, 499, 500,
       501, 503, 504, 505, 506, 508, 510, 511, 512, 513, 514, 519, 520,
       521, 522, 523, 529, 539, 540, 899])

In [30]:
# Create Household ID

lv9 = mos_lv9.copy()

lv9["HH_ID"] = (
    lv9["FSU_Serial_No"].astype(str)
    + "_"
    + lv9["Sample_Household_No"].astype(str)
)

In [31]:
# Create Household Weights

hh_weight_lv9 = (
    lv9.groupby("HH_ID")["Multiplier"]
    .first()
    .reset_index()
)

In [32]:
# Welfare Category Mapping

welfare_map = {

    # Education
    400:"Education",
    401:"Education",
    402:"Education",
    404:"Education",
    405:"Education",
    406:"Education",

    # Health
    410:"Health",
    411:"Health",
    412:"Health",
    413:"Health",

    # Hygiene
    450:"Hygiene",
    451:"Hygiene",
    452:"Hygiene",
    453:"Hygiene",
    454:"Hygiene",
    455:"Hygiene",
    456:"Hygiene",
    457:"Hygiene",
    465:"Hygiene",
    466:"Hygiene",
    467:"Hygiene",
    471:"Hygiene",

    # Transport
    500:"Transport",
    501:"Transport",
    503:"Transport",
    504:"Transport",
    505:"Transport",
    506:"Transport",
    508:"Transport",
    510:"Transport",
    511:"Transport",
    512:"Transport",
    513:"Transport",

    # Housing
    520:"Housing",
    522:"Housing",
    523:"Housing",
    539:"Housing"
}

In [33]:
# Keep Welfare Items Only

lv9 = lv9[
    lv9["Item_Code_9_1_to_11_4"]
    .isin(welfare_map.keys())
].copy()

print(lv9.shape)

(3311484, 22)

In [34]:
# Assign Welfare Categories

lv9["Welfare_Category"] = (
    lv9["Item_Code_9_1_to_11_4"]
    .map(welfare_map)
)

# Create Household Welfare Matrix

welfare_hh = (
    lv9.pivot_table(
        index=[
            "HH_ID",
            "State",
            "District",
            "Sector"
        ],
        columns="Welfare_Category",
        values="Value_Rs_9_1_to_11_4",
        aggfunc="sum",
        fill_value=0
    )
    .reset_index()
)

In [35]:
# Ensure All Welfare Columns Exist

welfare_cols = [
    "Education",
    "Health",
    "Hygiene",
    "Transport",
    "Housing"
]

for col in welfare_cols:
    if col not in welfare_hh.columns:
        welfare_hh[col] = 0

In [36]:
# Merge Household Weights
welfare_hh = welfare_hh.merge(
    hh_weight_lv9,
    on="HH_ID",
    how="left"
)

# Total Welfare Expenditure
welfare_hh["Total_Welfare_Expense"] = (
    welfare_hh[welfare_cols]
    .sum(axis=1)
)

# Welfare Category Count
welfare_hh["Welfare_Category_Count"] = (
    (
        welfare_hh[welfare_cols] > 0
    ).sum(axis=1)
)

# Welfare Diversity Score
welfare_hh["Welfare_Diversity_Score"] = (
    welfare_hh["Welfare_Category_Count"]
    / len(welfare_cols)
)

# Welfare Spending Score
welfare_hh["Welfare_Spending_Score"] = (
    welfare_hh["Total_Welfare_Expense"]
    .rank(pct=True)
)

# Welfare Index
welfare_hh["Welfare_Index"] = (
      0.60 * welfare_hh["Welfare_Spending_Score"]
    + 0.40 * welfare_hh["Welfare_Diversity_Score"]
)

In [37]:
# Select Final Columns

final_cols = [

    "HH_ID",
    "State",
    "District",
    "Sector",
    "Multiplier",

    "Education",
    "Health",
    "Hygiene",
    "Transport",
    "Housing",

    "Total_Welfare_Expense",
    "Welfare_Category_Count",
    "Welfare_Diversity_Score",
    "Welfare_Spending_Score",
    "Welfare_Index"
]

welfare_hh = welfare_hh[final_cols]

In [38]:
# Final dataset of MOSPI Level-9 Dataset (HCES)

welfare_hh.head(5)

,HH_ID,State,District,Sector,Multiplier,Education,Health,Hygiene,Transport,Housing,Total_Welfare_Expense,Welfare_Category_Count,Welfare_Diversity_Score,Welfare_Spending_Score,Welfare_Index
0,22300_1,34,2,2,57436,0,0,3345,14300,30000,47645,3,0.6,0.865059,0.759036
1,22300_10,34,2,2,28599,0,0,825,1300,14000,16125,3,0.6,0.626862,0.616117
2,22300_11,34,2,2,28599,0,0,910,2700,8000,11610,3,0.6,0.547590,0.568554
3,22300_12,34,2,2,28599,38000,0,1105,2700,8000,49805,4,0.8,0.872700,0.843620
4,22300_13,34,2,2,28599,47000,47000,885,2950,11000,108835,5,1.0,0.963659,0.978196

In [39]:
# Checking Null Values

welfare_hh.isnull().sum()

HH_ID                      0
State                      0
District                   0
Sector                     0
Multiplier                 0
Education                  0
Health                     0
Hygiene                    0
Transport                  0
Housing                    0
Total_Welfare_Expense      0
Welfare_Category_Count     0
Welfare_Diversity_Score    0
Welfare_Spending_Score     0
Welfare_Index              0
dtype: int64

In [40]:
welfare_hh.describe()

,State,District,Sector,Multiplier,Education,Health,Hygiene,Transport,Housing,Total_Welfare_Expense,Welfare_Category_Count,Welfare_Diversity_Score,Welfare_Spending_Score,Welfare_Index
count,227074.000000,227074.000000,227074.000000,2.270740e+05,2.270740e+05,2.270740e+05,227074.000000,227074.000000,227074.000000,2.270740e+05,227074.000000,227074.000000,227074.000000,227074.000000
mean,18.871002,15.740367,1.415371,1.122840e+05,1.308359e+04,5.399743e+03,751.141359,1916.245281,3186.922919,2.433765e+04,3.387116,0.677423,0.500002,0.570971
std,9.395226,13.204231,0.492787,8.054289e+04,2.921721e+04,2.905444e+04,603.082205,2487.870650,6348.126039,4.638186e+04,0.815274,0.163055,0.288676,0.224661
min,1.000000,1.000000,1.000000,3.690000e+02,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+01,1.000000,0.200000,0.000007,0.080004
25%,9.000000,6.000000,1.000000,5.780500e+04,0.000000e+00,0.000000e+00,390.000000,450.000000,0.000000,3.672000e+03,3.000000,0.600000,0.249996,0.393150
50%,19.000000,12.000000,1.000000,1.145305e+05,1.910000e+03,0.000000e+00,600.000000,1300.000000,1500.000000,9.623000e+03,3.000000,0.600000,0.499993,0.576876
75%,27.000000,22.000000,2.000000,1.510780e+05,1.495000e+04,0.000000e+00,907.000000,2410.000000,4000.000000,2.716700e+04,4.000000,0.800000,0.750002,0.759284
max,37.000000,71.000000,2.000000,2.366902e+06,1.550300e+06,2.315000e+06,16360.000000,155750.000000,200000.000000,2.372023e+06,5.000000,1.000000,1.000000,0.999997

In [41]:
# Final shape MOSPI Level-5 Dataset (HCES)

welfare_hh.shape

(227074, 15)

In [42]:
# Checking Duplicate Values

welfare_hh.duplicated().sum()

np.int64(0)

### MOSPI Level-13 Dataset (HCES)

        The MOSPI Level-13 dataset captures household-level durable and asset ownership data, including transport, 
        housing, furniture, and medical equipment.
        
        It transforms raw item codes into meaningful asset categories for measuring long-term economic stability.
        
        In this project, it forms the basis for constructing Asset Diversity and Wealth Structure indicators.
        
        This dataset is essential for analyzing structural inequality and household wealth distribution patterns.

In [43]:
lv13 = pd.read_csv("Level - 13 (Section 14).csv")
print(lv13.shape)

(4951749, 27)

In [44]:
lv13.head(5)

,Survey_Name,Year,FSU_Serial_No,Sector,State,NSS_Region,District,Stratum,Sub_stratum,Panel,...,Level,ITEM_CODE,FIRST_PURCHASE_NUMBER,PURCHASED_ON_HIRE,FIRST_PURCHASE_VALUE,REPAIR_COST,SECOND_HAND_NUMBER,SECOND_HAND_VALUE,TOTAL_EXPENDITURE,MULTIPLIER
0,HCES,2024,46667,1,1,12,6,13,1,2,...,13,442,2.0,NaN,300.0,NaN,NaN,NaN,300,16669
1,HCES,2024,46667,1,1,12,6,13,1,2,...,13,552,NaN,NaN,NaN,400.0,NaN,NaN,400,16669
2,HCES,2024,46667,1,1,12,6,13,1,2,...,13,554,NaN,2.0,600.0,NaN,NaN,NaN,600,16669
3,HCES,2024,46667,1,1,12,6,13,1,2,...,13,570,NaN,2.0,2200.0,NaN,NaN,NaN,2200,16669
4,HCES,2024,46667,1,1,12,6,13,1,2,...,13,573,NaN,2.0,900.0,NaN,NaN,NaN,900,16669

In [45]:
lv13.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4951749 entries, 0 to 4951748
Data columns (total 27 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Survey_Name              object
 1   Year                     int64
 2   FSU_Serial_No            int64
 3   Sector                   int64
 4   State                    int64
 5   NSS_Region               int64
 6   District                 int64
 7   Stratum                  int64
 8   Sub_stratum              int64
 9   Panel                    int64
 10  Sub_sample               int64
 11  FOD_Sub_Region           int64
 12  Sample_SU_No             int64
 13  Sample_Sub_Division_No   float64
 14  Second_Stage_Stratum_No  int64
 15  Sample_Household_No      int64
 16  Questionnaire_No         object
 17  Level                    int64
 18  ITEM_CODE                int64
 19  FIRST_PURCHASE_NUMBER    float64
 20  PURCHASED_ON_HIRE        float64
 21  FIRST_PURCHASE_VALUE     float64
 22  REPAIR_COST              float64
 23  SECOND_HAND_NUMBER       float64
 24  SECOND_HAND_VALUE        float64
 25  TOTAL_EXPENDITURE        int64
 26  MULTIPLIER               int64
dtypes: float64(7), int64(18), object(2)
memory usage: 1020.0+ MB

In [46]:
lv13.isnull().sum()

Survey_Name                      0
Year                             0
FSU_Serial_No                    0
Sector                           0
State                            0
NSS_Region                       0
District                         0
Stratum                          0
Sub_stratum                      0
Panel                            0
Sub_sample                       0
FOD_Sub_Region                   0
Sample_SU_No                     0
Sample_Sub_Division_No     4914349
Second_Stage_Stratum_No          0
Sample_Household_No              0
Questionnaire_No                 0
Level                            0
ITEM_CODE                        0
FIRST_PURCHASE_NUMBER      4106718
PURCHASED_ON_HIRE          3413843
FIRST_PURCHASE_VALUE       1500788
REPAIR_COST                2952808
SECOND_HAND_NUMBER         4947957
SECOND_HAND_VALUE          4942352
TOTAL_EXPENDITURE                0
MULTIPLIER                       0
dtype: int64

In [47]:
# checking item code

np.sort(lv13['ITEM_CODE'].unique())

array([ 35,  36,  37,  40,  41,  42,  43,  44,  45,  46,  47,  48,  50,
        97,  99, 432, 440, 441, 442, 550, 551, 552, 553, 554, 555, 556,
       557, 559, 560, 561, 562, 563, 564, 569, 570, 571, 572, 573, 579,
       580, 581, 582, 583, 584, 585, 586, 587, 588, 590, 591, 592, 599,
       600, 601, 602, 603, 604, 609, 610, 611, 619, 620, 621, 622, 623,
       624, 625, 629, 630, 631, 632, 633, 639, 640, 641, 642, 643, 649])

In [48]:
# Create Household ID

lv13["HH_ID"] = (
    lv13["FSU_Serial_No"].astype(str)
    + "_"
    + lv13["Sample_Household_No"].astype(str)
)

In [49]:
# Keep Required Columns Only

lv13 = lv13[
    [
        "HH_ID",
        "State",
        "District",
        "Sector",
        "MULTIPLIER",
        "ITEM_CODE",
        "TOTAL_EXPENDITURE"
    ]
].copy()

In [50]:
# Asset Category Mapping

category_map = {

    # Personal Goods
    35:"Personal_Goods",
    440:"Personal_Goods",
    441:"Personal_Goods",
    442:"Personal_Goods",
    554:"Personal_Goods",
    620:"Personal_Goods",
    621:"Personal_Goods",
    622:"Personal_Goods",
    623:"Personal_Goods",
    624:"Personal_Goods",
    625:"Personal_Goods",

    # Transport Assets
    600:"Transport_Assets",
    601:"Transport_Assets",
    602:"Transport_Assets",
    603:"Transport_Assets",
    604:"Transport_Assets",

    # Sports Assets
    36:"Sports_Assets",
    37:"Sports_Assets",
    432:"Sports_Assets",

    # Medical Equipment
    40:"Medical_Equipment",
    41:"Medical_Equipment",
    42:"Medical_Equipment",
    610:"Medical_Equipment",
    611:"Medical_Equipment",

    # Household Appliances
    43:"Household_Appliances",
    44:"Household_Appliances",
    45:"Household_Appliances",
    46:"Household_Appliances",
    47:"Household_Appliances",
    48:"Household_Appliances",
    580:"Household_Appliances",
    581:"Household_Appliances",
    582:"Household_Appliances",
    583:"Household_Appliances",
    584:"Household_Appliances",
    585:"Household_Appliances",
    586:"Household_Appliances",
    587:"Household_Appliances",
    591:"Household_Appliances",
    592:"Household_Appliances",

    # Furniture
    550:"Furniture_Fixtures",
    551:"Furniture_Fixtures",
    552:"Furniture_Fixtures",
    553:"Furniture_Fixtures",
    555:"Furniture_Fixtures",
    556:"Furniture_Fixtures",
    557:"Furniture_Fixtures",

    # Residential Durables
    630:"Residential_Durables",
    631:"Residential_Durables",
    632:"Residential_Durables",
    633:"Residential_Durables",

    # Jewellery
    640:"Jewellery_Assets",
    641:"Jewellery_Assets",
    642:"Jewellery_Assets",
    643:"Jewellery_Assets"
}

In [51]:
# Assign Asset Categories

lv13["Category"] = (
    lv13["ITEM_CODE"]
    .map(category_map)
)

lv13 = lv13[
    lv13["Category"].notna()
].copy()

print(lv13.shape)

(2639067, 8)

In [52]:
# Household Information

hh_info = (
    lv13
    .groupby("HH_ID")
    .agg({
        "State":"first",
        "District":"first",
        "Sector":"first",
        "MULTIPLIER":"first"
    })
    .reset_index()
)

hh_info.rename(
    columns={
        "MULTIPLIER":"Multiplier"
    },
    inplace=True
)

In [53]:
# Asset Expenditure Matrix

asset_exp = (
    lv13.pivot_table(
        index="HH_ID",
        columns="Category",
        values="TOTAL_EXPENDITURE",
        aggfunc="sum",
        fill_value=0
    )
    .reset_index()
)

In [54]:
# Merge Household Information

asset_hh = hh_info.merge(
    asset_exp,
    on="HH_ID",
    how="inner"
)

In [55]:
# Ensure All Asset Columns Exist

asset_cols = [
    "Personal_Goods",
    "Transport_Assets",
    "Sports_Assets",
    "Medical_Equipment",
    "Household_Appliances",
    "Furniture_Fixtures",
    "Residential_Durables",
    "Jewellery_Assets"
]

for col in asset_cols:
    if col not in asset_hh.columns:
        asset_hh[col] = 0

In [56]:
# Total Asset Expenditure
asset_hh["Total_Durable_Expenditure"] = (
    asset_hh[asset_cols]
    .sum(axis=1)
)

# Asset Category Count
asset_hh["Asset_Category_Count"] = (
    asset_hh[asset_cols]
    .gt(0)
    .sum(axis=1)
)

# Asset Diversity Score
asset_hh["Asset_Diversity_Score"] = (
    asset_hh["Asset_Category_Count"]
    / len(asset_cols)
)

# Log Asset Value
asset_hh["Log_Asset_Value"] = np.log1p(
    asset_hh["Total_Durable_Expenditure"]
)

# Asset Wealth Score
asset_hh["Asset_Wealth_Score"] = (
    asset_hh["Log_Asset_Value"]
    .rank(pct=True)
)

# Durable Asset Index
asset_hh["Durable_Asset_Index"] = (
      0.50 * asset_hh["Asset_Wealth_Score"]
    + 0.50 * asset_hh["Asset_Diversity_Score"]
)

In [57]:
# Final Dataset

final_cols = [

    "HH_ID",
    "State",
    "District",
    "Sector",
    "Multiplier",

    "Personal_Goods",
    "Transport_Assets",
    "Sports_Assets",
    "Medical_Equipment",
    "Household_Appliances",
    "Furniture_Fixtures",
    "Residential_Durables",
    "Jewellery_Assets",

    "Total_Durable_Expenditure",
    "Asset_Category_Count",
    "Asset_Diversity_Score",
    "Asset_Wealth_Score",
    "Durable_Asset_Index",
    "Log_Asset_Value"
]

asset_hh = asset_hh[final_cols]

In [58]:
# Final dataset of MOSPI Level-13 Dataset (HCES)

asset_hh.head(5)

,HH_ID,State,District,Sector,Multiplier,Personal_Goods,Transport_Assets,Sports_Assets,Medical_Equipment,Household_Appliances,Furniture_Fixtures,Residential_Durables,Jewellery_Assets,Total_Durable_Expenditure,Asset_Category_Count,Asset_Diversity_Score,Asset_Wealth_Score,Durable_Asset_Index,Log_Asset_Value
0,22300_1,34,2,2,57436,7180,470180,600,0,7500,1380,6150,1900,494890,7,0.875,0.998912,0.936956,13.112093
1,22300_10,34,2,2,28599,580,0,500,4500,1650,650,1800,450,10130,7,0.875,0.532465,0.703733,9.223355
2,22300_11,34,2,2,28599,2600,4600,800,0,700,630,0,600,9930,6,0.750,0.524994,0.637497,9.203416
3,22300_12,34,2,2,28599,1080,3790,800,0,1500,620,1250,600,9640,7,0.875,0.514148,0.694574,9.173780
4,22300_13,34,2,2,28599,700,3500,800,0,1750,120,0,450,7320,6,0.750,0.414871,0.582436,8.898502

In [59]:
asset_hh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225194 entries, 0 to 225193
Data columns (total 19 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   HH_ID                      225194 non-null  object
 1   State                      225194 non-null  int64
 2   District                   225194 non-null  int64
 3   Sector                     225194 non-null  int64
 4   Multiplier                 225194 non-null  int64
 5   Personal_Goods             225194 non-null  int64
 6   Transport_Assets           225194 non-null  int64
 7   Sports_Assets              225194 non-null  int64
 8   Medical_Equipment          225194 non-null  int64
 9   Household_Appliances       225194 non-null  int64
 10  Furniture_Fixtures         225194 non-null  int64
 11  Residential_Durables       225194 non-null  int64
 12  Jewellery_Assets           225194 non-null  int64
 13  Total_Durable_Expenditure  225194 non-null  int64
 14  Asset_Category_Count       225194 non-null  int64
 15  Asset_Diversity_Score      225194 non-null  float64
 16  Asset_Wealth_Score         225194 non-null  float64
 17  Durable_Asset_Index        225194 non-null  float64
 18  Log_Asset_Value            225194 non-null  float64
dtypes: float64(4), int64(14), object(1)
memory usage: 32.6+ MB

In [60]:
# Checking Null Values

asset_hh.isnull().sum()

HH_ID                        0
State                        0
District                     0
Sector                       0
Multiplier                   0
Personal_Goods               0
Transport_Assets             0
Sports_Assets                0
Medical_Equipment            0
Household_Appliances         0
Furniture_Fixtures           0
Residential_Durables         0
Jewellery_Assets             0
Total_Durable_Expenditure    0
Asset_Category_Count         0
Asset_Diversity_Score        0
Asset_Wealth_Score           0
Durable_Asset_Index          0
Log_Asset_Value              0
dtype: int64

In [61]:
asset_hh.describe()

,State,District,Sector,Multiplier,Personal_Goods,Transport_Assets,Sports_Assets,Medical_Equipment,Household_Appliances,Furniture_Fixtures,Residential_Durables,Jewellery_Assets,Total_Durable_Expenditure,Asset_Category_Count,Asset_Diversity_Score,Asset_Wealth_Score,Durable_Asset_Index,Log_Asset_Value
count,225194.000000,225194.000000,225194.000000,2.251940e+05,225194.000000,2.251940e+05,225194.000000,225194.000000,225194.000000,225194.000000,2.251940e+05,2.251940e+05,2.251940e+05,225194.000000,225194.000000,225194.000000,225194.000000,225194.000000
mean,18.833521,15.769066,1.414878,1.119546e+05,3564.179401,4.178333e+03,322.806585,151.623471,2146.617037,1393.477033,3.237929e+03,3.658728e+03,1.865369e+04,5.440340,0.680043,0.500002,0.590022,9.104780
std,9.389362,13.223556,0.492702,7.988882e+04,7121.992873,3.166163e+04,824.980171,786.860532,4160.895312,3432.936991,1.688612e+04,1.601570e+04,4.593196e+04,1.603625,0.200453,0.288676,0.217488,1.214644
min,1.000000,1.000000,1.000000,3.690000e+02,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,8.000000e+00,1.000000,0.125000,0.000004,0.062502,2.197225
25%,9.000000,6.000000,1.000000,5.769600e+04,550.000000,2.900000e+02,0.000000,0.000000,350.000000,0.000000,1.000000e+02,2.500000e+02,4.370000e+03,4.000000,0.500000,0.249947,0.436790,8.382747
50%,19.000000,12.000000,1.000000,1.144500e+05,1340.000000,1.700000e+03,0.000000,0.000000,950.000000,520.000000,7.000000e+02,6.500000e+02,9.250000e+03,6.000000,0.750000,0.499762,0.611242,9.132487
75%,27.000000,22.000000,2.000000,1.508820e+05,3100.000000,3.641500e+03,440.000000,0.000000,2350.000000,1400.000000,2.800000e+03,2.300000e+03,1.980000e+04,7.000000,0.875000,0.749996,0.762574,9.893488
max,37.000000,71.000000,2.000000,2.366902e+06,237400.000000,4.521250e+06,60850.000000,100000.000000,244820.000000,201200.000000,1.926000e+06,2.071500e+06,4.532950e+06,8.000000,1.000000,1.000000,0.999991,15.326884

In [62]:
# Final shape MOSPI Level-13 Dataset (HCES)

asset_hh.shape

(225194, 19)

In [63]:
# Checking Duplicate Values

asset_hh.duplicated().sum()

np.int64(0)

### Integration of MOSPI Level 5, Level 9, and Level 13 Datasets
### Combining Multiple Data Levels for Comprehensive Analysis

In [64]:
# MOSPI Level-5 Dataset (HCES)
food_hh.columns

Index(['HH_ID', 'State', 'District', 'Sector', 'Beverages', 'Cereals',
       'Edible_Oil', 'Egg_Fish_Meat', 'Fruits', 'Milk_Products', 'Pulses',
       'Spices', 'Sugar', 'Vegetables', 'Multiplier', 'Total_Food_Value',
       'OutOfHome_Food_Value', 'Food_Items_Count', 'Diet_Diversity_Score',
       'Nutrition_Score', 'Protein_Value', 'Protein_Score',
       'Food_Security_Score', 'OutOfHome_Ratio',
       'Overall_Food_Wellbeing_Index'],
      dtype='object')

In [65]:
# MOSPI Level-9 Dataset (HCES)
welfare_hh.columns

Index(['HH_ID', 'State', 'District', 'Sector', 'Multiplier', 'Education',
       'Health', 'Hygiene', 'Transport', 'Housing', 'Total_Welfare_Expense',
       'Welfare_Category_Count', 'Welfare_Diversity_Score',
       'Welfare_Spending_Score', 'Welfare_Index'],
      dtype='object')

In [66]:
# MOSPI Level-13 Dataset (HCES)
asset_hh.columns

Index(['HH_ID', 'State', 'District', 'Sector', 'Multiplier', 'Personal_Goods',
       'Transport_Assets', 'Sports_Assets', 'Medical_Equipment',
       'Household_Appliances', 'Furniture_Fixtures', 'Residential_Durables',
       'Jewellery_Assets', 'Total_Durable_Expenditure', 'Asset_Category_Count',
       'Asset_Diversity_Score', 'Asset_Wealth_Score', 'Durable_Asset_Index',
       'Log_Asset_Value'],
      dtype='object')

In [67]:
print('MOSPI Level-5 Dataset Shape',food_hh.shape)
print('MOSPI Level-9 Dataset Shape',welfare_hh.shape)
print('MOSPI Level-13 Dataset Shape',asset_hh.shape)

MOSPI Level-5 Dataset Shape (226445, 25)
MOSPI Level-9 Dataset Shape (227074, 15)
MOSPI Level-13 Dataset Shape (225194, 19)

In [68]:
# Find Common Households

common_hh = (
    set(food_hh["HH_ID"])
    &
    set(welfare_hh["HH_ID"])
    &
    set(asset_hh["HH_ID"])
)

print("Common HH:", len(common_hh))

Common HH: 224768

In [69]:
# Keep Only Common Households

food_final = food_hh[
    food_hh["HH_ID"].isin(common_hh)
].copy()

welfare_final = welfare_hh[
    welfare_hh["HH_ID"].isin(common_hh)
].copy()

asset_final = asset_hh[
    asset_hh["HH_ID"].isin(common_hh)
].copy()

In [70]:
# Verify Multipliers Match

mult_check = (
    food_final[["HH_ID", "Multiplier"]]
    .rename(columns={"Multiplier":"Food_Mult"})
    .merge(
        welfare_final[["HH_ID","Multiplier"]]
        .rename(columns={"Multiplier":"Welfare_Mult"}),
        on="HH_ID"
    )
    .merge(
        asset_final[["HH_ID","Multiplier"]]
        .rename(columns={"Multiplier":"Asset_Mult"}),
        on="HH_ID"
    )
)

In [71]:
# Remove Bad Households

bad_hh = mult_check[
    (mult_check["Food_Mult"] != mult_check["Welfare_Mult"])
    |
    (mult_check["Food_Mult"] != mult_check["Asset_Mult"])
]["HH_ID"]

print("Bad HH:", len(bad_hh))

Bad HH: 40

In [72]:
# Remove Them

food_final = food_final[
    ~food_final["HH_ID"].isin(bad_hh)
]

welfare_final = welfare_final[
    ~welfare_final["HH_ID"].isin(bad_hh)
]

asset_final = asset_final[
    ~asset_final["HH_ID"].isin(bad_hh)
]

In [73]:
# Merge Datasets

master = (
    food_final
    .merge(
        welfare_final.drop(
            columns=[
                "State",
                "District",
                "Sector",
                "Multiplier"
            ]
        ),
        on="HH_ID",
        how="inner"
    )
    .merge(
        asset_final.drop(
            columns=[
                "State",
                "District",
                "Sector",
                "Multiplier"
            ]
        ),
        on="HH_ID",
        how="inner"
    )
)

print(master.shape)

(224728, 49)

In [74]:
# Create Welfare Index

master["Welfare_Index"] = (
    0.5 *
    master["Welfare_Diversity_Score"]
    +
    0.5 *
    master["Total_Welfare_Expense"].rank(pct=True)
)

In [75]:
# Normalize All Three Pillars

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

master[
    [
        "Food_Index_N",
        "Welfare_Index_N",
        "Asset_Index_N"
    ]
] = scaler.fit_transform(
    master[
        [
            "Overall_Food_Wellbeing_Index",
            "Welfare_Index",
            "Durable_Asset_Index"
        ]
    ]
)

In [76]:
# Create Composite Wellbeing Index

master["Economic_Wellbeing_Index"] = (
      0.40 * master["Food_Index_N"]
    + 0.30 * master["Welfare_Index_N"]
    + 0.30 * master["Asset_Index_N"]
)

# Create Wellbeing Classes
master["Wellbeing_Class"] = pd.qcut(
    master["Economic_Wellbeing_Index"],
    q=5,
    labels=[
        "Very Low",
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

In [77]:
# Final Dataset (HCES)

master.head(5)

,HH_ID,State,District,Sector,Beverages,Cereals,Edible_Oil,Egg_Fish_Meat,Fruits,Milk_Products,...,Asset_Category_Count,Asset_Diversity_Score,Asset_Wealth_Score,Durable_Asset_Index,Log_Asset_Value,Food_Index_N,Welfare_Index_N,Asset_Index_N,Economic_Wellbeing_Index,Wellbeing_Class
0,22300_1,34,2,2,601.0,4207.0,656.0,1422.0,845.0,860.0,...,7,0.875,0.998912,0.936956,13.112093,0.993005,0.702419,0.932762,0.887756,Very High
1,22300_10,34,2,2,226.0,895.0,174.0,348.0,450.0,290.0,...,7,0.875,0.532465,0.703733,9.223355,0.784739,0.569205,0.683986,0.689853,High
2,22300_11,34,2,2,256.0,1625.0,172.0,854.0,415.0,440.0,...,6,0.750,0.524994,0.637497,9.203416,0.929010,0.524805,0.613334,0.713046,High
3,22300_12,34,2,2,353.0,2235.0,270.0,1170.0,425.0,590.0,...,7,0.875,0.514148,0.694574,9.173780,0.971496,0.817800,0.674217,0.836204,Very High
4,22300_13,34,2,2,216.0,1455.0,228.0,648.0,430.0,440.0,...,6,0.750,0.414871,0.582436,8.898502,0.926440,0.979679,0.554601,0.830860,Very High

In [78]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224728 entries, 0 to 224727
Data columns (total 54 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   HH_ID                         224728 non-null  object
 1   State                         224728 non-null  int64
 2   District                      224728 non-null  int64
 3   Sector                        224728 non-null  int64
 4   Beverages                     224728 non-null  float64
 5   Cereals                       224728 non-null  float64
 6   Edible_Oil                    224728 non-null  float64
 7   Egg_Fish_Meat                 224728 non-null  float64
 8   Fruits                        224728 non-null  float64
 9   Milk_Products                 224728 non-null  float64
 10  Pulses                        224728 non-null  float64
 11  Spices                        224728 non-null  float64
 12  Sugar                         224728 non-null  float64
 13  Vegetables                    224728 non-null  float64
 14  Multiplier                    224728 non-null  int64
 15  Total_Food_Value              224728 non-null  float64
 16  OutOfHome_Food_Value          224728 non-null  float64
 17  Food_Items_Count              224728 non-null  int64
 18  Diet_Diversity_Score          224728 non-null  float64
 19  Nutrition_Score               224728 non-null  float64
 20  Protein_Value                 224728 non-null  float64
 21  Protein_Score                 224728 non-null  float64
 22  Food_Security_Score           224728 non-null  float64
 23  OutOfHome_Ratio               224728 non-null  float64
 24  Overall_Food_Wellbeing_Index  224728 non-null  float64
 25  Education                     224728 non-null  int64
 26  Health                        224728 non-null  int64
 27  Hygiene                       224728 non-null  int64
 28  Transport                     224728 non-null  int64
 29  Housing                       224728 non-null  int64
 30  Total_Welfare_Expense         224728 non-null  int64
 31  Welfare_Category_Count        224728 non-null  int64
 32  Welfare_Diversity_Score       224728 non-null  float64
 33  Welfare_Spending_Score        224728 non-null  float64
 34  Welfare_Index                 224728 non-null  float64
 35  Personal_Goods                224728 non-null  int64
 36  Transport_Assets              224728 non-null  int64
 37  Sports_Assets                 224728 non-null  int64
 38  Medical_Equipment             224728 non-null  int64
 39  Household_Appliances          224728 non-null  int64
 40  Furniture_Fixtures            224728 non-null  int64
 41  Residential_Durables          224728 non-null  int64
 42  Jewellery_Assets              224728 non-null  int64
 43  Total_Durable_Expenditure     224728 non-null  int64
 44  Asset_Category_Count          224728 non-null  int64
 45  Asset_Diversity_Score         224728 non-null  float64
 46  Asset_Wealth_Score            224728 non-null  float64
 47  Durable_Asset_Index           224728 non-null  float64
 48  Log_Asset_Value               224728 non-null  float64
 49  Food_Index_N                  224728 non-null  float64
 50  Welfare_Index_N               224728 non-null  float64
 51  Asset_Index_N                 224728 non-null  float64
 52  Economic_Wellbeing_Index      224728 non-null  float64
 53  Wellbeing_Class               224728 non-null  category
dtypes: category(1), float64(30), int64(22), object(1)
memory usage: 91.1+ MB

In [79]:
# Final Dataset Checking null value

master.isnull().sum()

HH_ID                           0
State                           0
District                        0
Sector                          0
Beverages                       0
Cereals                         0
Edible_Oil                      0
Egg_Fish_Meat                   0
Fruits                          0
Milk_Products                   0
Pulses                          0
Spices                          0
Sugar                           0
Vegetables                      0
Multiplier                      0
Total_Food_Value                0
OutOfHome_Food_Value            0
Food_Items_Count                0
Diet_Diversity_Score            0
Nutrition_Score                 0
Protein_Value                   0
Protein_Score                   0
Food_Security_Score             0
OutOfHome_Ratio                 0
Overall_Food_Wellbeing_Index    0
Education                       0
Health                          0
Hygiene                         0
Transport                       0
Housing                         0
Total_Welfare_Expense           0
Welfare_Category_Count          0
Welfare_Diversity_Score         0
Welfare_Spending_Score          0
Welfare_Index                   0
Personal_Goods                  0
Transport_Assets                0
Sports_Assets                   0
Medical_Equipment               0
Household_Appliances            0
Furniture_Fixtures              0
Residential_Durables            0
Jewellery_Assets                0
Total_Durable_Expenditure       0
Asset_Category_Count            0
Asset_Diversity_Score           0
Asset_Wealth_Score              0
Durable_Asset_Index             0
Log_Asset_Value                 0
Food_Index_N                    0
Welfare_Index_N                 0
Asset_Index_N                   0
Economic_Wellbeing_Index        0
Wellbeing_Class                 0
dtype: int64

In [80]:
# Statistical Summary of final Dataset

master.describe()

,State,District,Sector,Beverages,Cereals,Edible_Oil,Egg_Fish_Meat,Fruits,Milk_Products,Pulses,...,Total_Durable_Expenditure,Asset_Category_Count,Asset_Diversity_Score,Asset_Wealth_Score,Durable_Asset_Index,Log_Asset_Value,Food_Index_N,Welfare_Index_N,Asset_Index_N,Economic_Wellbeing_Index
count,224728.000000,224728.000000,224728.000000,224728.000000,224728.000000,224728.000000,224728.000000,224728.000000,224728.000000,224728.000000,...,2.247280e+05,224728.000000,224728.000000,224728.000000,224728.000000,224728.000000,224728.000000,224728.000000,224728.000000,224728.000000
mean,18.824361,15.767305,1.414305,157.352515,1124.435692,137.577547,296.172066,166.939460,456.639538,418.728387,...,1.868401e+04,5.447376,0.680922,0.500729,0.590826,9.109309,0.744383,0.543773,0.563550,0.629950
std,9.388302,13.228655,0.492603,190.158009,889.214764,117.602544,429.130067,185.874133,544.764416,322.020027,...,4.597291e+04,1.596599,0.199575,0.288320,0.216820,1.209559,0.160149,0.233579,0.231278,0.163059
min,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000e+01,1.000000,0.125000,0.000011,0.062506,2.397895,0.000000,0.000000,0.000000,0.012398
25%,9.000000,6.000000,1.000000,50.000000,560.000000,75.000000,32.000000,55.000000,156.000000,212.000000,...,4.400000e+03,5.000000,0.625000,0.251630,0.437718,8.389587,0.642137,0.365056,0.400232,0.517331
50%,19.000000,12.000000,1.000000,105.000000,925.000000,119.000000,190.000000,110.000000,309.000000,348.000000,...,9.280000e+03,6.000000,0.750000,0.500835,0.611794,9.135725,0.756069,0.551019,0.585916,0.637642
75%,27.000000,22.000000,2.000000,192.000000,1434.000000,168.000000,390.000000,215.000000,565.000000,530.000000,...,1.982125e+04,7.000000,0.875000,0.750376,0.762847,9.894560,0.867326,0.736218,0.747042,0.750934
max,37.000000,71.000000,2.000000,5760.000000,23780.000000,19950.000000,35000.000000,6130.000000,64420.000000,8070.000000,...,4.532950e+06,8.000000,1.000000,1.000000,0.999991,15.326884,1.000000,1.000000,1.000000,0.999714

In [81]:
# Final Dataset Shape of (HCES)

master.shape

(224728, 54)

In [82]:
# Checking Duplicate Values

master.duplicated().sum()

np.int64(0)

### District Master Dataset

        The district dataset serves as a geospatial administrative reference layer containing standardized State and 
        District codes for India.
            
        It is used to ensure consistent spatial alignment and merging across MOSPI Level-5, Level-9, Level-13, and 
        external geospatial datasets.
            
        In this project, it enables accurate district-level aggregation and mapping of socio-economic indicators.
            
        This dataset is essential for building a unified geospatial framework for spatial inequality and hotspot analysis.

In [83]:
dist = pd.read_csv("district_data3.csv")

In [84]:
dist.sample(6)

     State code       State Name  District Name  District code
148           9    Uttar Pradesh      Firozabad             16
569          28   Andhra Pradesh  West Godavari              5
388          21           Odisha      Sambalpur              3
18            1  Jammu & Kashmir       Udhampur             19
118           8        Rajasthan         Sirohi             19
591          29       Karnataka         Shimoga             14

In [85]:
dist.shape

(699, 4)

In [86]:
# Create State Mapping

state_map = (
    dist[
        ["State code", "State Name"]
    ]
    .drop_duplicates()
)

state_map.columns = [
    "State",
    "State_Name"
]

In [87]:
# Create District Mapping

district_map_lookup = (
    dist[
        [
            "State code",
            "District code",
            "District Name"
        ]
    ]
    .drop_duplicates()
)

district_map_lookup.columns = [
    "State",
    "District",
    "District_Name"
]

In [88]:
# Merge State Names

master = master.merge(
    state_map,
    on="State",
    how="left"
)

# Merge District Names
master = master.merge(
    district_map_lookup,
    on=["State", "District"],
    how="left"
)

In [89]:
# Create Sector Names

sector_map = {
    1: "Rural",
    2: "Urban"
}

master["Sector_Name"] = (
    master["Sector"]
    .map(sector_map)
)

In [90]:
# Remove Numeric Codes

master = master.drop(
    columns=[
        "State",
        "District",
        "Sector"
    ]
)

In [91]:
master.sample(5)

,HH_ID,Beverages,Cereals,Edible_Oil,Egg_Fish_Meat,Fruits,Milk_Products,Pulses,Spices,Sugar,...,Durable_Asset_Index,Log_Asset_Value,Food_Index_N,Welfare_Index_N,Asset_Index_N,Economic_Wellbeing_Index,Wellbeing_Class,State_Name,District_Name,Sector_Name
15118,23509_1,410.0,1200.0,300.0,2050.0,470.0,690.0,360.0,270.0,220.0,...,0.813046,10.442930,0.973922,0.819915,0.800588,0.875720,Very High,Mizoram,Lunglei,Urban
137855,43909_13,40.0,945.0,65.0,160.0,75.0,350.0,390.0,126.0,240.0,...,0.858494,9.777414,0.749353,0.403643,0.849068,0.675554,Medium,Bihar,Sitamarhi,Rural
60169,26754_9,150.0,1010.0,72.0,18.0,110.0,508.0,602.0,186.0,74.0,...,0.911925,10.995428,0.802399,0.842802,0.906062,0.845619,Very High,Himachal Pradesh,Solan,Urban
174145,46566_15,20.0,315.0,65.0,30.0,0.0,455.0,330.0,101.0,243.0,...,0.380870,7.863651,0.596449,0.215738,0.339594,0.405179,Very Low,Punjab,Rupnagar,Rural
201571,48459_7,140.0,1118.0,80.0,445.0,395.0,260.0,552.0,155.0,65.0,...,0.518358,9.235131,0.854362,0.179688,0.486250,0.541526,Low,Andhra Pradesh,Sri Potti Sriramulu Nellore,Rural

In [92]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224728 entries, 0 to 224727
Data columns (total 54 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   HH_ID                         224728 non-null  object
 1   Beverages                     224728 non-null  float64
 2   Cereals                       224728 non-null  float64
 3   Edible_Oil                    224728 non-null  float64
 4   Egg_Fish_Meat                 224728 non-null  float64
 5   Fruits                        224728 non-null  float64
 6   Milk_Products                 224728 non-null  float64
 7   Pulses                        224728 non-null  float64
 8   Spices                        224728 non-null  float64
 9   Sugar                         224728 non-null  float64
 10  Vegetables                    224728 non-null  float64
 11  Multiplier                    224728 non-null  int64
 12  Total_Food_Value              224728 non-null  float64
 13  OutOfHome_Food_Value          224728 non-null  float64
 14  Food_Items_Count              224728 non-null  int64
 15  Diet_Diversity_Score          224728 non-null  float64
 16  Nutrition_Score               224728 non-null  float64
 17  Protein_Value                 224728 non-null  float64
 18  Protein_Score                 224728 non-null  float64
 19  Food_Security_Score           224728 non-null  float64
 20  OutOfHome_Ratio               224728 non-null  float64
 21  Overall_Food_Wellbeing_Index  224728 non-null  float64
 22  Education                     224728 non-null  int64
 23  Health                        224728 non-null  int64
 24  Hygiene                       224728 non-null  int64
 25  Transport                     224728 non-null  int64
 26  Housing                       224728 non-null  int64
 27  Total_Welfare_Expense         224728 non-null  int64
 28  Welfare_Category_Count        224728 non-null  int64
 29  Welfare_Diversity_Score       224728 non-null  float64
 30  Welfare_Spending_Score        224728 non-null  float64
 31  Welfare_Index                 224728 non-null  float64
 32  Personal_Goods                224728 non-null  int64
 33  Transport_Assets              224728 non-null  int64
 34  Sports_Assets                 224728 non-null  int64
 35  Medical_Equipment             224728 non-null  int64
 36  Household_Appliances          224728 non-null  int64
 37  Furniture_Fixtures            224728 non-null  int64
 38  Residential_Durables          224728 non-null  int64
 39  Jewellery_Assets              224728 non-null  int64
 40  Total_Durable_Expenditure     224728 non-null  int64
 41  Asset_Category_Count          224728 non-null  int64
 42  Asset_Diversity_Score         224728 non-null  float64
 43  Asset_Wealth_Score            224728 non-null  float64
 44  Durable_Asset_Index           224728 non-null  float64
 45  Log_Asset_Value               224728 non-null  float64
 46  Food_Index_N                  224728 non-null  float64
 47  Welfare_Index_N               224728 non-null  float64
 48  Asset_Index_N                 224728 non-null  float64
 49  Economic_Wellbeing_Index      224728 non-null  float64
 50  Wellbeing_Class               224728 non-null  category
 51  State_Name                    224728 non-null  object
 52  District_Name                 224728 non-null  object
 53  Sector_Name                   224728 non-null  object
dtypes: category(1), float64(30), int64(19), object(4)
memory usage: 91.1+ MB

### CPI (Consumer Price Index) Dataset

        The CPI dataset provides temporal price level data across states, sectors, and consumption groups, capturing 
        inflation dynamics in India.
            
        It is used to adjust nominal values into real economic terms, ensuring comparability of consumption and welfare
        indicators over time.
            
        In this project, it supports inflation correction for MOSPI consumption and expenditure variables to build 
        accurate wellbeing measures.
            
        This dataset is essential for integrating time-aware economic stability into spatial inequality and welfare modeling.

In [93]:
cpi = pd.read_excel("cpi_1061.xlsx")
print(cpi.shape)

(77652, 11)

In [94]:
cpi.head(5)

,baseyear,year,month_code,month,state,sector,group,subgroup,index,inflation,status
0,2012,2025,12,December,All India,Rural,Consumer Food Price,Consumer Food Price-Overall,198.5,-3.03,F
1,2012,2025,12,December,All India,Rural,Miscellaneous,Education,197.8,2.91,F
2,2012,2025,12,December,All India,Rural,Miscellaneous,Miscellaneous-Overall,203.4,6.60,F
3,2012,2025,12,December,All India,Rural,Miscellaneous,Personal Care and Effects,265.3,28.60,F
4,2012,2025,12,December,All India,Rural,Miscellaneous,Household Goods and Services,189.8,1.50,F

In [95]:
cpi.isnull().sum()

baseyear         0
year             0
month_code       0
month            0
state            0
sector           0
group            0
subgroup         0
index         2988
inflation     2988
status           0
dtype: int64

In [96]:
# Keep only 2024

cpi = cpi[
    cpi["year"] == 2024
].copy()

print(cpi.shape)
print(cpi["year"].unique())

(25884, 11)
[2024]

In [97]:
# Prepare State Names in Master

master["cpi_state"] = (
    master["State_Name"]
    .str.strip()
)

master["cpi_state"] = master["cpi_state"].replace({
    "Andaman & Nicobar Island": "Andaman & Nicobar Islands",
    "Ladakh": "Jammu & Kashmir"
})

In [98]:
# Verify State Matching

master_states = set(
    master["cpi_state"].unique()
)

cpi_states = set(
    cpi["state"].str.strip().unique()
)

print("MASTER NOT IN CPI")
print(master_states - cpi_states)

print("\nCPI NOT IN MASTER")
print(cpi_states - master_states)

MASTER NOT IN CPI
set()

CPI NOT IN MASTER
{'Dadra & Nagar Haveli', 'All India'}

In [99]:
# Create CPI Indicators
# Food CPI

food_cpi = (
    cpi[
        cpi["group"] == "Food and Beverages"
    ]
    .groupby("state")["index"]
    .mean()
    .reset_index()
)

food_cpi.columns = [
    "state",
    "Food_CPI"
]

In [100]:
# Housing CPI

housing_cpi = (
    cpi[
        cpi["group"] == "Housing"
    ]
    .groupby("state")["index"]
    .mean()
    .reset_index()
)

housing_cpi.columns = [
    "state",
    "Housing_CPI"
]

In [101]:
# Health CPI

health_cpi = (
    cpi[
        cpi["subgroup"] == "Health"
    ]
    .groupby("state")["index"]
    .mean()
    .reset_index()
)

health_cpi.columns = [
    "state",
    "Health_CPI"
]

In [102]:
# Education CPI

education_cpi = (
    cpi[
        cpi["subgroup"] == "Education"
    ]
    .groupby("state")["index"]
    .mean()
    .reset_index()
)

education_cpi.columns = [
    "state",
    "Education_CPI"
]

In [103]:
# Transport CPI

transport_cpi = (
    cpi[
        cpi["subgroup"] == "Transport and Communication"
    ]
    .groupby("state")["index"]
    .mean()
    .reset_index()
)

transport_cpi.columns = [
    "state",
    "Transport_CPI"
]

# Fuel CPI
fuel_cpi = (
    cpi[
        cpi["group"] == "Fuel and Light"
    ]
    .groupby("state")["index"]
    .mean()
    .reset_index()
)

fuel_cpi.columns = [
    "state",
    "Fuel_CPI"
]

In [104]:
# General CPI

general_cpi = (
    cpi[
        cpi["group"] == "General"
    ]
    .groupby("state")["index"]
    .mean()
    .reset_index()
)

general_cpi.columns = [
    "state",
    "General_CPI"
]

# Misc CPI

misc_cpi = (
    cpi[
        cpi["group"] == "Miscellaneous"
    ]
    .groupby("state")["index"]
    .mean()
    .reset_index()
)

misc_cpi.columns = [
    "state",
    "Misc_CPI"
]

In [105]:
# Create Inflation Indicators

food_inf = (
    cpi[
        cpi["group"] == "Food and Beverages"
    ]
    .groupby("state")["inflation"]
    .mean()
    .reset_index()
)

food_inf.columns = [
    "state",
    "Food_Inflation"
]

# General Inflation

general_inf = (
    cpi[
        cpi["group"] == "General"
    ]
    .groupby("state")["inflation"]
    .mean()
    .reset_index()
)

general_inf.columns = [
    "state",
    "General_Inflation"
]

In [106]:
# Build Final CPI Dataset

cpi_final = (
    food_cpi
    .merge(housing_cpi,
           on="state",
           how="outer")
    .merge(health_cpi,
           on="state",
           how="outer")
    .merge(education_cpi,
           on="state",
           how="outer")
    .merge(transport_cpi,
           on="state",
           how="outer")
    .merge(fuel_cpi,
           on="state",
           how="outer")
    .merge(general_cpi,
           on="state",
           how="outer")
    .merge(misc_cpi,
           on="state",
           how="outer")
    .merge(food_inf,
           on="state",
           how="left")
    .merge(general_inf,
           on="state",
           how="left")
)

print(cpi_final.shape)
cpi_final.head()

(37, 11)

,state,Food_CPI,Housing_CPI,Health_CPI,Education_CPI,Transport_CPI,Fuel_CPI,General_CPI,Misc_CPI,Food_Inflation,General_Inflation
0,All India,195.517308,180.241667,194.041667,186.633333,168.783333,176.186111,190.780556,184.052381,6.795235,4.927778
1,Andaman & Nicobar Islands,207.413889,209.716667,NaN,NaN,NaN,156.602778,193.005556,176.430556,5.369444,2.303333
2,Andhra Pradesh,201.121581,196.000000,185.105556,220.497222,183.986111,162.605556,196.388889,190.872222,6.703419,4.924722
3,Arunachal Pradesh,189.500000,NaN,NaN,NaN,NaN,233.758333,195.100000,185.841667,5.986667,4.957500
4,Assam,183.959188,179.608333,198.791667,184.158333,168.658333,245.452778,192.916667,182.328571,5.307970,5.422778

In [107]:
cpi_final.isnull().sum()

state                 0
Food_CPI              0
Housing_CPI           1
Health_CPI           14
Education_CPI        14
Transport_CPI        14
Fuel_CPI              0
General_CPI           0
Misc_CPI              0
Food_Inflation        0
General_Inflation     0
dtype: int64

In [108]:
# Merge CPI Into Master

master = master.merge(
    cpi_final,
    left_on="cpi_state",
    right_on="state",
    how="left"
)

print(master.shape)

(224728, 66)

In [109]:
# Set display option to show all rows
pd.set_option('display.max_rows', None)

# Now run your check
print(master.isnull().sum())

# Optional: Reset the display option back to default afterwards
pd.reset_option('display.max_rows')

HH_ID                               0
Beverages                           0
Cereals                             0
Edible_Oil                          0
Egg_Fish_Meat                       0
Fruits                              0
Milk_Products                       0
Pulses                              0
Spices                              0
Sugar                               0
Vegetables                          0
Multiplier                          0
Total_Food_Value                    0
OutOfHome_Food_Value                0
Food_Items_Count                    0
Diet_Diversity_Score                0
Nutrition_Score                     0
Protein_Value                       0
Protein_Score                       0
Food_Security_Score                 0
OutOfHome_Ratio                     0
Overall_Food_Wellbeing_Index        0
Education                           0
Health                              0
Hygiene                             0
Transport                           0
Housing                             0
Total_Welfare_Expense               0
Welfare_Category_Count              0
Welfare_Diversity_Score             0
Welfare_Spending_Score              0
Welfare_Index                       0
Personal_Goods                      0
Transport_Assets                    0
Sports_Assets                       0
Medical_Equipment                   0
Household_Appliances                0
Furniture_Fixtures                  0
Residential_Durables                0
Jewellery_Assets                    0
Total_Durable_Expenditure           0
Asset_Category_Count                0
Asset_Diversity_Score               0
Asset_Wealth_Score                  0
Durable_Asset_Index                 0
Log_Asset_Value                     0
Food_Index_N                        0
Welfare_Index_N                     0
Asset_Index_N                       0
Economic_Wellbeing_Index            0
Wellbeing_Class                     0
State_Name                          0
District_Name                       0
Sector_Name                         0
cpi_state                           0
state                               0
Food_CPI                            0
Housing_CPI                      2984
Health_CPI                      25057
Education_CPI                   25057
Transport_CPI                   25057
Fuel_CPI                            0
General_CPI                         0
Misc_CPI                            0
Food_Inflation                      0
General_Inflation                   0
dtype: int64

In [110]:
# Handle Missing CPI Values

for col in [
    "Health_CPI",
    "Education_CPI",
    "Transport_CPI"
]:
    master[col] = master[col].fillna(
        master["Misc_CPI"]
    )

housing_median = (
    master["Housing_CPI"]
    .median()
)

master["Housing_CPI"] = (
    master["Housing_CPI"]
    .fillna(housing_median)
)

In [111]:
# Check Missing Values

cpi_cols = [
    "Food_CPI",
    "Housing_CPI",
    "Health_CPI",
    "Education_CPI",
    "Transport_CPI",
    "Fuel_CPI",
    "General_CPI",
    "Food_Inflation",
    "General_Inflation"
]

print(
    master[cpi_cols]
    .isnull()
    .sum()
)

Food_CPI             0
Housing_CPI          0
Health_CPI           0
Education_CPI        0
Transport_CPI        0
Fuel_CPI             0
General_CPI          0
Food_Inflation       0
General_Inflation    0
dtype: int64

In [112]:
# Create Normalized CPI Features

for col in [
    "Food_CPI",
    "Housing_CPI",
    "Health_CPI",
    "Education_CPI",
    "Transport_CPI",
    "Fuel_CPI",
    "General_CPI"
]:
    master[col + "_N"] = (
        master[col]
        /
        master[col].mean()
    )

In [113]:
# Create Real (Inflation Adjusted) Indicators

master["Housing_Burden"] = (
    master["Housing"]
    /
    master["Housing_CPI"]
)

master["Real_Food_Index"] = (
    master["Food_Index_N"]
    /
    master["Food_CPI_N"]
)

master["Real_Housing_Index"] = (
    master["Housing_Burden"]
    /
    master["Housing_CPI_N"]
)

master["Real_Wellbeing"] = (
    (
        master["Food_Index_N"]
        /
        master["Food_CPI_N"]
    )
    +
    (
        master["Welfare_Index_N"]
        /
        master["General_CPI_N"]
    )
    +
    master["Asset_Index_N"]
) / 3

In [114]:
# Final Validation

print(master.shape)

print(
    master.isnull().sum()[
        master.isnull().sum() > 0
    ]
)

master[
    [
        "Real_Wellbeing",
        "Food_Inflation",
        "General_Inflation"
    ]
].describe()

(224728, 77)
Series([], dtype: int64)

       Real_Wellbeing  Food_Inflation  General_Inflation
count   224728.000000   224728.000000      224728.000000
mean         0.617669        6.715478           4.964851
std          0.167102        1.056495           0.860583
min          0.010446        0.470833           2.290278
25%          0.501226        6.126282           4.305278
50%          0.624765        6.745043           4.924722
75%          0.740987        7.353611           5.517222
max          1.060856       11.575556           7.609722

In [115]:
master.shape

(224728, 77)

In [116]:
# Log-scaled income proxy stability

master["Log_Food_Value"] = np.log1p(master["Total_Food_Value"])
master["Log_Welfare_Expense"] = np.log1p(master["Total_Welfare_Expense"])
master["Log_Asset_Value_Final"] = np.log1p(master["Total_Durable_Expenditure"])

# Inequality / imbalance indicator

master["Consumption_Imbalance"] = (
    master["Food_Index_N"]
    - master["Asset_Index_N"]
).abs()

# Poverty-risk proxy (important for research)

master["Low_Wellbeing_Flag"] = (
    master["Economic_Wellbeing_Index"] < 0.4
).astype(int)

# High-end consumption flag

master["Luxury_Household_Flag"] = (
    master["Jewellery_Assets"] > master["Jewellery_Assets"].quantile(0.90)
).astype(int)

# Rural–Urban gap feature

master["Urban_Premium"] = (
    master.groupby("Sector_Name")["Economic_Wellbeing_Index"]
    .transform("mean")
)

# Composite vulnerability index

master["Vulnerability_Index"] = (
    1 - master["Economic_Wellbeing_Index"]
) * (1 + master["Housing_Burden"])

In [117]:
# Set display option to show all rows
pd.set_option('display.max_rows', None)

# Now run your check
print(master.isnull().sum())

# Optional: Reset the display option back to default afterwards
pd.reset_option('display.max_rows')

HH_ID                           0
Beverages                       0
Cereals                         0
Edible_Oil                      0
Egg_Fish_Meat                   0
Fruits                          0
Milk_Products                   0
Pulses                          0
Spices                          0
Sugar                           0
Vegetables                      0
Multiplier                      0
Total_Food_Value                0
OutOfHome_Food_Value            0
Food_Items_Count                0
Diet_Diversity_Score            0
Nutrition_Score                 0
Protein_Value                   0
Protein_Score                   0
Food_Security_Score             0
OutOfHome_Ratio                 0
Overall_Food_Wellbeing_Index    0
Education                       0
Health                          0
Hygiene                         0
Transport                       0
Housing                         0
Total_Welfare_Expense           0
Welfare_Category_Count          0
Welfare_Diversity_Score         0
Welfare_Spending_Score          0
Welfare_Index                   0
Personal_Goods                  0
Transport_Assets                0
Sports_Assets                   0
Medical_Equipment               0
Household_Appliances            0
Furniture_Fixtures              0
Residential_Durables            0
Jewellery_Assets                0
Total_Durable_Expenditure       0
Asset_Category_Count            0
Asset_Diversity_Score           0
Asset_Wealth_Score              0
Durable_Asset_Index             0
Log_Asset_Value                 0
Food_Index_N                    0
Welfare_Index_N                 0
Asset_Index_N                   0
Economic_Wellbeing_Index        0
Wellbeing_Class                 0
State_Name                      0
District_Name                   0
Sector_Name                     0
cpi_state                       0
state                           0
Food_CPI                        0
Housing_CPI                     0
Health_CPI                      0
Education_CPI                   0
Transport_CPI                   0
Fuel_CPI                        0
General_CPI                     0
Misc_CPI                        0
Food_Inflation                  0
General_Inflation               0
Food_CPI_N                      0
Housing_CPI_N                   0
Health_CPI_N                    0
Education_CPI_N                 0
Transport_CPI_N                 0
Fuel_CPI_N                      0
General_CPI_N                   0
Housing_Burden                  0
Real_Food_Index                 0
Real_Housing_Index              0
Real_Wellbeing                  0
Log_Food_Value                  0
Log_Welfare_Expense             0
Log_Asset_Value_Final           0
Consumption_Imbalance           0
Low_Wellbeing_Flag              0
Luxury_Household_Flag           0
Urban_Premium                   0
Vulnerability_Index             0
dtype: int64

In [118]:
master.shape

(224728, 85)

In [119]:
master.head(5)

,HH_ID,Beverages,Cereals,Edible_Oil,Egg_Fish_Meat,Fruits,Milk_Products,Pulses,Spices,Sugar,...,Real_Housing_Index,Real_Wellbeing,Log_Food_Value,Log_Welfare_Expense,Log_Asset_Value_Final,Consumption_Imbalance,Low_Wellbeing_Flag,Luxury_Household_Flag,Urban_Premium,Vulnerability_Index
0,22300_1,601.0,4207.0,656.0,1422.0,845.0,860.0,1497.0,661.0,307.0,...,170.983518,0.846480,9.396488,10.771554,13.112093,0.060244,0,0,0.666071,18.953009
1,22300_10,226.0,895.0,174.0,348.0,450.0,290.0,280.0,162.0,61.0,...,79.792309,0.655791,8.037220,9.688188,9.223355,0.100753,0,0,0.666071,24.604800
2,22300_11,256.0,1625.0,172.0,854.0,415.0,440.0,507.0,231.0,156.0,...,45.595605,0.662706,8.497806,9.359708,9.203416,0.315677,0,0,0.666071,13.131459
3,22300_12,353.0,2235.0,270.0,1170.0,425.0,590.0,970.0,272.0,172.0,...,45.595605,0.790917,8.848796,10.815891,9.173780,0.297280,0,0,0.666071,7.495569
4,22300_13,216.0,1455.0,228.0,648.0,430.0,440.0,689.0,207.0,163.0,...,62.693957,0.789379,8.480944,11.597597,8.898502,0.371839,0,0,0.666071,10.579229

### Final Integrated Analytical Dataset (EDA & Machine Learning)

        The final analytical dataset was created by integrating MOSPI HCES Level-5, Level-9, Level-13, district administrative 
        data, and Consumer Price Index (CPI) information into a unified household-level database. 
        
        The integrated dataset contains household identifiers, socio-economic indicators, inflation-adjusted variables, and 
        engineered features designed for exploratory data analysis (EDA), spatial analysis, and machine learning.

### The dataset is organized into the following feature groups:

        Household Identifier:- Household ID (HH_ID).
        
        Food Consumption Features:- Food expenditure by category (Cereals, Pulses, Milk Products, Fruits, Vegetables, Edible Oil, 
                                    Sugar, Spices, Beverages, Egg/Fish/Meat), total food expenditure, dietary diversity, 
                                    nutrition score, protein score, food security score, out-of-home food expenditure, and 
                                    Overall Food Wellbeing Index.
        
        Welfare Features:- Expenditure on Education, Health, Hygiene, Housing, and Transport, together with Welfare Diversity 
                           Score, Welfare Spending Score, and Welfare Index.
                           
        Household Asset Features:- Household durable assets including transport assets, household appliances, furniture, 
                                   residential durables, jewellery, medical equipment, sports assets, and personal goods, 
                                   summarized through Asset Diversity Score, Asset Wealth Score, Durable Asset Index, 
                                   and logarithmic asset value.
                                   
        Economic Wellbeing Indicators:- Normalized Food, Welfare, and Asset indices combined into the Economic Wellbeing Index 
                                        and household Wellbeing Class.
                                        
        Administrative and Spatial Variables:- State, district, sector (Rural/Urban), and household multiplier used for spatial 
                                               aggregation and district-level analysis.
                                               
        Macroeconomic Variables:- State-level Consumer Price Index (Food, Housing, Health, Education, Transport, Fuel, General, 
                                    and Miscellaneous CPI) and corresponding inflation indicators.
                                  
        Inflation-Adjusted Indicators:- Real Food Index, Real Housing Index, and Real Wellbeing, constructed using CPI-adjusted 
                                        expenditure measures.
                                        
        Machine Learning Features:- Engineered variables including Housing Burden, Consumption Imbalance, Vulnerability Index, 
                                    Urban Premium, Luxury Household Flag, Low Wellbeing Flag, and logarithmic transformations of 
                                    expenditure variables.

        The final integrated dataset provides a multidimensional representation of household consumption, welfare, 
        asset ownership, and inflation-adjusted economic conditions, forming the foundation for exploratory data analysis,
        spatial hotspot detection, econometric modeling, and machine learning-based wellbeing prediction.